### ISSUE TITLE
the distribution position is wrong in scatterChart due to the scatter point position calculation changed

### ISSUE THREAD

**Issue by Alex--wu** [novus/nvd3#1164]
Since the commit in Mar 6, 2015 'scatter point position is calculated based on the overall page position of the container now...', the position of scatter calculation is changed. Before it is base on the container, now it is base on the overall page. But the calculation in scatterChart has not been updated. The problem is in line 317 of scatterChart.js

**Comment by Alex--wu** [comment]
I can fix it by recalculate the POS in scatterChart. But there is noway now to know the position of scatter point based on the container. My opinion is keep both.

**Comment by liquidpele** [comment]
Can you provide a jsfiddle showing the issue using the master branch code?   You can use rawgit.com to link to the build files in master.

**Comment by Alex--wu** [comment]
https://jsfiddle.net/wushengyuan/qmxtvy1z/

**Comment by liquidpele** [comment]
Ah, do you mean how the colored lines that appear on hover that are supposed to go from the point to each axis are off?   Yea I haven't had a chance to fix but I had seen it before...   if you already looked into it and know how to fix please send a pull request!

**Comment by Alex--wu** [comment]
Yes that is what I mean! I will fix it soon today. Do you know what other chart is using the scatter position? Can you tell me why you change the position to base on the overall page?

**Comment by liquidpele** [comment]
Okay, so this was also an issue brought up in https://github.com/novus/nvd3/issues/971 so I closed that old one and we'll track this particular issue here.   

The position is sent up the hover events to the tooltip position code, so the tooltips expect position to be based on the page.  That was done because the browsers make it a lot easier to position things that way... they account for scroll and all kinds of stuff for us, where calculating it ourselves based on relative position was a nightmare and we had like 10 different tooltip position bugs previously.  

Thus if you change the position for those, don't change what position is passed up to the tooltips :)

**Comment by Alex--wu** [comment]
okay so I will keep both position(base on page and base on container). I
keep the current key 'pos' for the position base on the page. And I will
create the key 'posObj' for the position base on the container. Does it
make sense for you? Do you have better key name for it?

2015-07-24 14:40 GMT+02:00 liquidpele <notifications@github.com>:

**Comment by liquidpele** [comment]
relativePos maybe?

**Comment by Alex--wu** [comment]
y

**Comment by Alex--wu** [comment]
hi liquidpele,

When I am checking why my build test failed, I have a question for you about the position about the mouse even in scatter.js.
You just modified the position base on page only for the case when useVoronoi==ture. But when useVoronoi == false, it is still using the old positin which is relative on the container. Is it a mistake or you have other purpose?

**Comment by liquidpele** [comment]
that's probably a mistake

**Comment by Alex--wu** [comment]
ok. I checked, not other charts are using the scatter position when useVoronoi == false. I will make the pull request after my work.
