### ISSUE TITLE
Rewrite tooltip positioning

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#1183]
I am rewriting the tooltip positioning to simplify the code and remove a lot of recalculations that are unnecessary and are introducing bugs.

What do you think about instead of having north, south, east and west gravities, have northeast, northwest, southeast and southwest? This will simplify greatly when calculating the tooltip positioning, because then if someone scrolls to the bottom right of the screen I just have to change the gravity from the default to northeast, displaying all the tooltip on the screen.

**Comment by liquidpele** [comment]
Hah, well to be honest I haven't ever tried changing the gravity, when I redid the tooltips I tried to just keep that stuff the same as it was since I was already modifying so much.  Maybe @robinfhu can chime in on that since they might use it at novus...    if not I can play with it at some point but I don't know when.

**Comment by RenatoUtsch** [comment]
I almost finished this rewrite, today or tomorrow I'll make a pull request, because the positioning is buggy in some cases.

The idea is to remove the 'n', 'w', 'e', and 's' gravities and replace them with 'ne', 'nw', 'se' and 'sw' gravities.

**Comment by RenatoUtsch** [comment]
I made a pull request.
