### ISSUE TITLE
Pie Chart percentage can exceed 100%

### ISSUE THREAD

**Issue by sudotliu** [novus/nvd3#1320]
While somewhat rare, a chart's total percentages can exceed 100% due to rounding error.

It seems like NVD3's pie chart rounds up from .5 so the following situation occurs:
<img width="1232" alt="screen shot 2015-10-24 at 8 58 41 am" src="https://cloud.githubusercontent.com/assets/4766414/10711402/ea25c0ae-7a2e-11e5-874d-2f8210ed83a1.png">

You can recreate this by opening pie chart in live code, adding `.labelType("percent")` to the chart functions and then setting this as your data:
```
 [
      {
        "label": "Seven",
        "value" : 80.5
      } ,
      {
        "label": "Eight",
        "value" : 19.5
      }
]
```

**Comment by sudotliu** [comment]
Thinking about a solution, without considering float percentage values, I think one would have to keep track of the percentages that compute to exactly a multiple of .5 and then adjust them based on the total percentage at the end.

This kind of further obfuscates how percentages are calculated though, so perhaps float percentages with low precision are the way to go in terms of default behavior.

**Comment by liquidpele** [comment]
There isn't really a great way to handle this automatically because the system is too customizable.  You can override the tooltips and the data formatters, so you could always adjust it yourself as needed, but no matter what you'll always have to do a bit of rounding.  

The best solution, if it really bugs you, is to probably fix the data to be rounded and add up to exactly 100 before handing it to nvd3.

**Comment by sudotliu** [comment]
Thanks!
