### ISSUE TITLE
MultiBarChart with time series data

### ISSUE THREAD

**Issue by anabelengp** [novus/nvd3#1349]
I am trying to draw a chart showing events over time for multiple subjects. A visual representation of the amount of events that occur at the same time is important for me. I thought the best way to do this was to have a MultiBarChart with a time scale. Without that time scale, dates with no events wouldn't be represented in the x axis.

Searching through issues I came across #275, that mentions multiBarTimeSeriesChart model and changes MultiBar xScale from linear to ordinal. I think [multiBarTimeSeriesChart](https://github.com/novus/nvd3/blob/v1.2.1/src/models/multiBarTimeSeriesChart.js) is what I need but, what happened to it in v1.7.1??

Is there another way to have this? perhaps a new *MultiHistoricalBarChart* model?

**Comment by liquidpele** [comment]
It was removed, because multibar has the ability to line up next to each other so they are inherently ordinal, you'd have to restrict it to only stack if you wanted it on a line and at that point you might as well just let historicalBarChart be stackable...    

However, you can always just include that old model file in your page if you just wanted to use it, it should just register itself and should still work as far as I'm aware.

**Comment by anabelengp** [comment]
Thank you! in the end I simulated the time scale by creating a discrete xDomain for the current multiBarChart model with a tick for every point in time of my interval
