### ISSUE TITLE
Date labels on the x axis are not aligned with interactive line

### ISSUE THREAD

**Issue by kavwang** [novus/nvd3#1375]
I searched on Google for the issue and had some work-around trick on it. But the result is still not so precise. 

**Reproduced code**: http://jsfiddle.net/ja8dzqoq/

**Comment by liquidpele** [comment]
I don't see anything wrong with your example jsfiddle, can you explain your issue in more detail please?

**Comment by liquidpele** [comment]
PS:  date labels will usually not align perfectly with the data line because you have rounded things to a day but D3 takes the time into account too when plotting the chart.   If you want to only use dates and ignore time, then you should filter the data to strip off all time before giving it to the chart.

**Comment by kavwang** [comment]
OK, I got it. Thank you for your explaining.
