### ISSUE TITLE
NVD3 releases

### ISSUE THREAD

**Issue by mgalloue** [novus/nvd3#1383]
Hi @liquidpele, I really don't know where I can ask question about NVD3. Is there a forum, a blog or do you haven a email for this kind of request?
Currently my question is: when a new NVD3 realease will be available? What is the strategy adopted on this side? 

Thanks

**Comment by liquidpele** [comment]
This is the place, there isn't really a mailing list or anything.   The strategy is I make a release whenever I have the time and feel like it's a good time to do it :p 

Novus could be more organized, I'm just a volunteer and don't work for them so this is all on my free time.   I've been meaning to make a new release though... it's just hectic right now due to the holiday season and lots on my plate.  Hopefully soon :)

**Comment by mgalloue** [comment]
Ok good :). Thanks for the quick answer.
