### ISSUE TITLE
lineChart and multiBarChart axis is not consistent for the same data

### ISSUE THREAD

**Issue by atais** [novus/nvd3#1477]
The issue can be observed in this plunker: http://plnkr.co/edit/ouiIDZ

Basically I put some data and display it with two different types of charts:
- lineChart
- multiBarChart

For the reasons I do not understand the x-axis is not consistent in both graphs, **for the same data.** The separators are drawn  in different places. Overall it makes it harder to compare data on different graphs.

How could this be solved? Is it a library bug?

**Comment by liquidpele** [comment]
Each nvd3 model adjusts data/margins/etc in its own way... but ultimately d3 decides on what labels to show on the axis, so it's mostly automatic according to the data.  It's not really a bug, just a side effect of the automatic niceties of d3... otherwise you'd have to manually keep track of what labels to show yourself, and that kind of defeats the purpose of having a tool handle gruntwork for you.

**Comment by atais** [comment]
Sorry, is there a way to do it manually then?
