### ISSUE TITLE
Some chart: Set top margin is not working

### ISSUE THREAD

**Issue by thienhv295** [novus/nvd3#1585]
I try to set top margin for some chart, but it's not working (it work fine with right, bottom, left exclude top margin). Please check link demo below:

[https://jsfiddle.net/thienhv295/wouy3qLx/](https://jsfiddle.net/thienhv295/wouy3qLx/)

Thank you.

**Comment by ovvn** [comment]
Same thing. tested in multibar chart. Margin.top isn't set up properly

**Comment by scottlowe** [comment]
Same problem here. I'm using version 1.8.2, and setting the top margin appears to have no effect.

**Comment by zag2art** [comment]
+1

**Comment by DeWenS** [comment]
+1

**Comment by fctsvirus** [comment]
+1

**Comment by zheoreh** [comment]
+1

**Comment by Tarlord** [comment]
Does not working in 1.8.0, 1.8.1 versions also(probably old bug)

**Comment by MaestroSc** [comment]
+1

**Comment by art-emm** [comment]
+1

**Comment by Yska** [comment]
+1

**Comment by ovvn** [comment]
I've found that if there's a legend on a chart then margin.top is being overwritten with `legend.height()` in many charts. That's why user specified top margin is ignored.
https://github.com/novus/nvd3/blob/master/src/models/cumulativeLineChart.js#L224
https://github.com/novus/nvd3/blob/master/src/models/historicalBarChart.js#L119
https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L191
https://github.com/novus/nvd3/blob/master/src/models/linePlusBarChart.js#L236
https://github.com/novus/nvd3/blob/master/src/models/multiBarChart.js#L171
https://github.com/novus/nvd3/blob/master/src/models/multiBarHorizontalChart.js#L162
https://github.com/novus/nvd3/blob/master/src/models/pieChart.js#L121
https://github.com/novus/nvd3/blob/master/src/models/scatterChart.js#L169
https://github.com/novus/nvd3/blob/master/src/models/stackedAreaChart.js#L169
https://github.com/novus/nvd3/blob/master/src/models/discreteBarChart.js#L118
@liquidpele should the top margin be overwritten in all charts with legend?

**Comment by ovvn** [comment]
There're two approaches
1. **Not to overwrite the top margin & availableHeight depending on a legend's height**. In this case user has a full control over the look of the chart. So he can set a top margin in a way that will prevent the chart and legend from overlapping.
2. **Overwrite the top margin & availableHeight only in case the legend's height is bigger than the top margin.** In this case user's specified top margin will be overwritten when the legend's height is bigger than the margin in order to prevent the overlapping.

I made two pull request for each of the case respectively.
