### ISSUE TITLE
 data:87 Uncaught TypeError: chart.tooltipContent is not a function

### ISSUE THREAD

**Issue by guganselvaraj** [novus/nvd3#1733]
Im a very beginner to django and stuck some where ! help me out ! 

The above issue is addressed here http://stackoverflow.com/questions/35125110/django-nvd3-chart-tooltipcontent-is-not-a-function, which i tried its perfectly fine on the local machine but when i deploy it on my production server the new installation of bower and its components happen where the new content.html and piechart.html has the same old chart.tooltipContent which should be replaced with the new one ! how would i do it on production deployment ???

FYI : My server is AWS : Elasticbeanstalk 
 
How to perform the changes mentioned in this link : http://stackoverflow.com/questions/35125110/django-nvd3-chart-tooltipcontent-is-not-a-function in a production server ! please throw some light on it ! :D

**Comment by liquidpele** [comment]
This looks like an issue with django-nvd3, not with nvd3... you'll have to open the issue with the appropriate project.    Basically, if you want to fix it yourself you'll have to look in the python site-packages (or wherever you have your modules) for the python-nvd3 and django-nvd3 modules and edit those to use the correct option calls...  otherwise those projects need to be updated to use the correct option calls for nvd3.

**Comment by guganselvaraj** [comment]
Hey thanks for the prompt reply yar ! :+1:
