### ISSUE TITLE
Color of pins does not coincide with selected area on area chart

### ISSUE THREAD

**Issue by e-olga** [novus/nvd3#1876]
We had got an issue with 'nvd3' on area chart

![widget legent](https://cloud.githubusercontent.com/assets/22497746/20710888/c2516f86-b64d-11e6-894c-86d1e191df4a.png)

If number of criterion>0, the area is available on the chart and pin color is the same as color of criterion.
If number of criterion=0, the area is not shown on widget, but the pin is and overlapped the previous one.
For instance, the area refers to 'System issue' (in blue), but its pin is overlapped by 'IE Issue' and 'To Investigate' pins.
So, the last one is shown on the graph.

**Expected**, that pins refer to the correspondent area.

**Comment by bgth** [comment]
Hi, The points are getting the colors. But because the values are zeros, they are getting overlapped on the same point. So, in the above case, the color of "system issue" is getting drawn, but because the previous values are zero, the color which gets drawn first remains on top and all others go in the background.

**Comment by liquidpele** [comment]
merged the PR made to fix this.
