### ISSUE TITLE
wrong data points positions after doing a transition

### ISSUE THREAD

**Issue by mvidailhet** [novus/nvd3#2018]
After doing a transition by changing the data, it seems that the data points are not at the right place anymore. It looks like the scale hasn't been updated for them.
If you remove the "duration" option, it works again, but there is no more transition on the line.
![screen shot 2017-04-18 at 16 57 57](https://cloud.githubusercontent.com/assets/4079962/25142598/ce0ad442-2467-11e7-9228-fb9b5fab89e4.png)

Here is the codepen: https://codepen.io/mvidailhet/pen/RVWyxo

**Comment by rameshvisolve** [comment]
Can please look into this issue, if you knows. https://github.com/krispo/angular-nvd3/issues/659

**Comment by lavinia-k** [comment]
Experienced a similar bug with (multi)line charts and interactiveGuideline, where the guideline points seem to be stuck in their previous position after a data update. Looks like this was working up to **nvd3-1.8.2**, but has stopped working from **nvd3-1.8.3** onwards.

I tried to replicate it here, but if you hover away from the chart for a while, the issue seems to disappear (which is not the case with the application I'm working with)...
http://plnkr.co/edit/bs9kjX?p=preview

Removing the '_duration_' option fixes it for me too, so I've done that for now.
