### ISSUE TITLE
export chart to pdf, png file?

### ISSUE THREAD

**Issue by lalunegrosse** [novus/nvd3#218]
Do you can provide export function to generate pdf, png, ... file from chart?

**Comment by crisp-github** [comment]
Can use phantomJS to convert the SVG to PNG.

**Comment by liquidpele** [comment]
Sure, you can do it anywhere you want provided your libs have the capability :package: 

For in-browser, you can still include the external CSS, like this:

http://spin.atomicobject.com/2014/01/21/convert-svg-to-png/

However, you'll have to do the work yourself... it's not a feature within nvd3 currently.. if anyone implements something please send us a pull request ^_^

**Comment by robinfhu** [comment]
The answer basically lies with PhantomJS.  It is the only tool we have used that can successfully convert a webpage into a PDF, nvd3 charts included.

**Comment by crisp-github** [comment]
We are using PhantomJS to get the images then TCPDF to create the PDF. Are you able to go straight from PhantomJS to PDF ?

**Comment by liquidpele** [comment]
PhantomJS just lets you generate the chart in what is essentially a headless browser, it doesn't transform anything itself, you'd still have to use another node/js library to export it to anything, so you'll have to see what exists out there or write something to fill the void.

**Comment by crisp-github** [comment]
@liquidpele I understand PhantomJS can output PNG, JPEG but not PDF however @robinfhu seems to imply it is the only tool that converts into PDF which is why I'm asking. Maybe Robin can provide more details. We currently use TCPDF to take the output from PhantomJS and convert that into PDF.

**Comment by robinfhu** [comment]
@crisp-github  I simply stated it's the only tool our company has *successfully* used to convert webpages to PDF.  If there is something else out there, we would love to use it.  

And PhantomJS can in fact output to PDF, I believe all you have to do is specify the '.pdf' extension when you pass in the output filename.

**Comment by portante** [comment]
We use https://github.com/exupero/saveSvgAsPng.

**Comment by crisp-github** [comment]
@robinfhu wow you are right. Sorry I had misunderstood PhantomJS could do this. I've not explored it much but it seems to be doing a good job of converting SVG into PDF. Thanks!

**Comment by philguiol** [comment]
Hello, coming late to this, but wanted to share a solution I came up with. Some conditions for my system:

- using PHP as backend
- reports are generated in-house, and then shared with customers on a need basis. This is not a viable solution for a customer facing issue (yet)
- using wkhtmltopdf to convert the file (does a good job of preserving css)

For some reason, wkhtmltopdf was not reading the <svg> content generated via javascript after page load (even when placing a long javascript delay), but if I grabbed the content of the <svg> tag and then pasted it, it worked. 
So there are 2 passes to each PDF generation. 
**Pass 1**
- Generate the charts as you normally would for a webpage. Set height and width of your charts and generate an ID code for them in the <svg> tag (e.g. `<svg style="height:200px;width:980px">`
- Create a function to send all charts to the backend with their ID code
- From the backend, create an html file with the content of the <svg>
**Pass 2**
- If the html chart file exists, get the file contents of that instead of generating the chart through nvd3

It's a bit of a cumbersome workaround, but it worked for me
