### ISSUE TITLE
Stacked Graph error when series contain different number of dates on the x-axis

### ISSUE THREAD

**Issue by homerlex** [novus/nvd3#220]
If I try to generate a stacked graph that has series that contain a different amount of dates I get the following js error:

```
Timestamp: 8/14/2013 4:23:24 PM
Error: TypeError: points[i][j] is undefined
Source File: http://nvd3.org/lib/d3.v2.js
Line: 5364
```

This can be duplicated by plugging in the follow JSON in the "Stacked Area Chart" Live Code example.

```
[
  {"key":"Fred",   
   "values":[
     [1291622400000,8.0],[1291708800000,8.0],[1291708800000,8.0]
   ]},
 {"key":"Bob",
  "values":[
    [1291622400000,8.0],[1291708800000,10.5]
  ]}]  

```

**Comment by jc0n** [comment]
I agree. This use case should definitely be supported. As @buddha314 said, time series data is a good example. Some series' data points may not be expected over certain time segments (ie. graph of metrics over time where a new metric is added at some point between the time range). The work around is to zero-fill the missing data which is probably not the optimal solution especially for large datasets.

**Comment by liquidpele** [comment]
So basically, that particular chart is designed to assume matching points... If someone e wants to change that send us a PR :)

**Comment by gesaleh** [comment]
I'm having the same issue my data come from sensors and time series they doesn't contain the same number of values
is there a WA ? or a way to overcome this issue

**Comment by demifeder** [comment]
I have the same issue and tried solving it by extrapolating my data over the whole time range, but then my program crashed because there was too much to plot (I believe). Any suggestions?

**Comment by liquidpele** [comment]
nvd3 currently has a requirement that series data on the same chart have a data point for each x axis.   This is because it tries to compare the series data equally for the tooltip.  If you want just lines chart without tooltip or points then you can accomplish that with just d3, or modify nvd3 to do what you need for your particular use cases.  However, nvd3 can't guess what kind of extrapolation or calculate what d3's interpolations are doing so it has no way to know what values to use if you don't provide them.
