### ISSUE TITLE
lineWithFocusChart crashes IE9

### ISSUE THREAD

**Issue by robertd** [novus/nvd3#250]
If you add more than 10 different data series it becomes painfully slow up to the point where IE9 constantly crashes. Not to speak if you have multiple focus charts on the same page. Chrome and FF works just fine... 

Anyone else noticed this?

**Comment by liquidpele** [comment]
I typically do IE10+, do we want to support IE9?   Personally I feel like, XP being long unsupported, anyone on IE9 should be expected to upgrade, but maybe that's just me...

**Comment by joshjordan** [comment]
While I agree with you in principle, the fact is that many companies
(especially in finance), are just stuck on IE9 and aren't going to move
from it any time soon. For the application I work on, we see ~5% of our
users on IE9, which is actually a larger share than IE10 (~2%). I don't
think a lot of folks are on IE10 because those that were willing to move to
IE10 have also moved to IE11 (~8% in our app).

This is reasonably representative of the IE9 browser usage share:
http://gs.statcounter.com/#browser_version_partially_combined-US-monthly-201401-201501

My opinion is that 5% of users is just too many to ignore. For instance, in
the application I work on, we would not be able to make a choice to use
something that wouldn't work on IE9. However, even if IE8 has a similar
market share in some slices, IE8 is too difficult to support. I'd make the
case that IE9 support is a reasonable goal. Thoughts?

**Comment by feltnerm** [comment]
Where I work we are currently investigating graphing libraries. NVD3 seems like a great option, but lack of IE9 support is a deal-breaker.

I am surprised because `canvas` is supported in IE9. Do we have a list of blockers for IE9 support?

**Comment by liquidpele** [comment]
Actually ie9 should work, I just don't test with it since I only require ie10.... If you see any issues with ie9 they should be easily fixable.

**Comment by joshjordan** [comment]
To say that another way, Mark: I don't think we have a list of blockers for
IE9, but do expect that the list is short, and we would very readily accept
pull requests that addressed any you ran across.

**Comment by feltnerm** [comment]
Good to know! Thanks! I'll report any findings, and am willing to provide pull requests/tests as they emerge.

FWIW, nvd3.org doesn't work well (at all?) on IE9.
