### ISSUE TITLE
Internet Explorer Lag

### ISSUE THREAD

**Issue by Rastii** [novus/nvd3#337]
When using multiple nv.model.line objects in Internet Explorer with a decent amount of data points (~100 per line), internet explorer (9 and 10) becomes laggy.

However, if one line is used the lag is not noticeable.

The lag is so great that it is very difficult to interact with anything else on the webapp.

Here is a plunker created to demonstrate the lagginess:
http://embed.plnkr.co/2z9wqcUU3a3foAoDh2XT/preview

**Comment by liquidpele** [comment]
I haven't seen this issue since picking up development, so marking closed unless someone can reproduce on the latest version

**Comment by robinfhu** [comment]
The issue might be 'voronoi', the calculations for those are intense.  I noticed a lot of revamping of the scatter.js code, so it may have been solved.

**Comment by liquidpele** [comment]
Yea I rewrote it due to chrome laggyness based on a blocks example that didn't have the issue.  I never saw IE laggyness but probably similar thing.

**Comment by mikyladewitt** [comment]
I am finding that when I have a line chart with a lot of data points (over 200ish, depends on what system I am testing on) my app gets incredibly sluggish and then crashes. When I use the other nvd3 charts, I do not have any issues with performance. I believe it happens with line charts specifically because the svg path element gets really long.

Also, I am always using the latest version of Chrome to test. I have not tried turning off voronoi yet, I may have to do that.

**Comment by liquidpele** [comment]
Try latest nvd3 version 1.8.1

**Comment by mikyladewitt** [comment]
@liquidpele Sorry for the delay in response.

So far the performance seems much better in 1.8.1 I have a line chart with almost 2000 samples in it and it is only lagging a little, but it hasn't crashed. I'm going to keep running to see if there is a limit that it will hit, but I would say this is much better! I also turned off voronoi so that is probably helping as well.
