### ISSUE TITLE
Tooltips for pie chart are broken in IE 10

### ISSUE THREAD

**Issue by piterimov** [novus/nvd3#48]
Tooltips for pie charts in Opera behave strangely (I used Opera 12). They appear and disappear when moving the mouse. Or appear when you click on a pie slice.
I do not know the reason for that, but it would be nice to fix it.
Thanks.

**Comment by dsm0880** [comment]
I found a very easy fix for those who don't want to introduce new JavaScript. Basically I over road the css class .nvtooltip, since the position is set to absolute I simply added a top attribute of ~50px (top:50px) and that seemed to get the tooltip off of the graph so the cursor no longer moves over it. I hope this helps someone.
