### ISSUE TITLE
Discussion of branching and dev practices

### ISSUE THREAD

**Issue by liquidpele** [novus/nvd3#755]
@portante @robinfhu @joshjordan 

Okay, so to avoid confusion/etc I'd like to propose the following:
1. We use the development branch for merging in changes and pull requests
2. When we want to cut a new version, we do it from development, merge that into master and gh-pages and then create a version tag off that (tag should be x.x.x semver format, without the v in front, as specified by bower's docs at http://bower.io/docs/creating-packages/#register)

Also, do we want to have commits go into our personal forked repos and go through a pull request, or just commit directly to the development branch?  I'm a big fan of code reviews so I kind of like doing pull requests as it gives that opportunity.

**Comment by portante** [comment]
@liquidpele, sounds fine to me, as I also like the code reviews.

I'd also like to see us lean heavily on unit tests.  We should work to make sure we have unit tests for the UI first, so that new changes to break existing contracts, which should ease user's concerns.

Second, I'd like to see this repo moved from `novus` organization to a community run organization for `nvd3`.  We recently moved cmaurer's angularjs-nvd3-directives repo to the community which had the benefit of automatic redirection and updates to all repos forked from it.

@robinfhu, @joshjordan, thoughts?

**Comment by robinfhu** [comment]
Unit tests are much needed, and I hope the tests we wrote in the tests/mocha directory are a good starting point.  Also, did you know that I added code coverage reporting?  It shows up in the 'coverage' folder when you run grunt.

Pull requests from a personal fork are a good idea.

Also, how does one move a repo from an organization?

**Comment by robinfhu** [comment]
Nevermind, reading https://help.github.com/articles/transferring-a-repository/ now

**Comment by tsenga** [comment]
What are your plans re: documentation? A while ago, I did various updates to the novus wiki - happy to recreate on nvd3-community wiki, unless there are other plans?

**Comment by joshjordan** [comment]
@liquidpele I'm a strong supporter of the dev branching workflow you laid out. Seems like there are no objections, so let's go with that.

@robinfhu Seems like we are pretty well aligned on testing. I think we should unit testing as a goal, and draw a line the sand. Since this code is relatively stable right now, let's say that we don't accept new functionality with proper test coverage, and for bug fixes, that we prefer unit tests to come along with the fix.

@portante Let's stick with the `novus` repository for now. There's enough confusion around `nvd3` as-is. 

@tsenga Thanks for your documentation. Let's keep it here and expand it. Do you have specific ideas in mind for documentation we need to improve (or stuff that isn't even covered)?

**Comment by robinfhu** [comment]
Just a note: I'm usually okay with configuration level changes (like README, bower.json, package.json, travis.yml) to go straight into 'master'.

**Comment by tsenga** [comment]
@joshjordan Key gaps in my mind are in the 'user guide' style material: in particular, more around the data model (& some of the gotchas), the interaction/event model and maybe an article focusing on updating charts with live data.

**Comment by liquidpele** [comment]
Yep, the two things I had on my plate to still document were:

1. the data layout and stream attribute options for each chart
2. the dispatches available for each chart

I'd like to make those auto-documented like the other options, just never got around to it yet.  Big fan of having this auto-generated into the docs, even if it's just placeholder, so you can easily keep track of things :)

**Comment by tsenga** [comment]
Agree. More auto-documentation the better. Then just a few introductory articles that guide the user through the high-level concepts and allow them to make use of the auto-generated detail.

**Comment by robinfhu** [comment]
Okay, so further thoughts:
while unit tests are very useful, it is also important to visually inspect the charts after a code change.  Lots of issues with tooltips could have been prevented if contributors took a quick look at the test pages I set up, before checking in code.  Also check them on each browser.

**Comment by joshjordan** [comment]
How are you guys feeling about the `development` branch? I thought it was a great idea, but I want to re-examine it now. There seems to be a lot of confusion by newcomers about what exactly is in master. This could be because:

1) `master` is so far behind `development` in terms of bug fixes
2) Our branching strategy is not obvious
3) No one will ever read a branching strategy no matter what we do

I believe #1 was a big contributor, but even barring that, I think we'll still see @liquidpele very often having to say "uh... did you try the development branch?". I'm beginning to think #3 may be true, and thinking we should just always have the latest good code in master. Thoughts?

**Comment by liquidpele** [comment]
Well, it's true that people try the master branch first even when they should try the development branch, but conversely people will also just grab what's in master when they want to download the library and then may have issues if master is under development and things are just temporarily broken.  Damned if you do, damned if you don't I guess...

**Comment by joshjordan** [comment]
I actually don't think that's a problem, though. Two reasons:

1) We had set unit testing as a goal, so new changes are much less likely
to be breaking than in the past.
2) It is okay to have between-release commits in master as long as it isn't
wildly broken. I *think* people know the risks they are taking when they
decide to compile the latest rather than use the pre-compiled release code.

**Comment by liquidpele** [comment]
I thought about this a little more and I guess it really does not make sense to have a stable master branch all the time so we should probably switch to master being the development branch especially since we don't really have any QA department working off of a testing branch or something similar

**Comment by liquidpele** [comment]
Meant to type "stale master branch" not "stable master branch"

**Comment by portante** [comment]
@joshjordan, I agree with your views, FWIW.  I find using feature branches for particularly complicated changes very useful, but most of what we do can be maintained on master with ever increasing use of unit tests.

I would like to see stable release branches used more, where we fix on master first, and then back port to the existing releases, where we only maintain one actively, perhaps two at the most.
