### ISSUE TITLE
Tooltip Ghosting issue (introduced in development branch)

### ISSUE THREAD

**Issue by robinfhu** [novus/nvd3#765]
An issue must have been introduced when all the tooltip code was changed in: https://github.com/novus/nvd3/commit/5cba3b425c5c

See my screenshot video:
![line chart tooltip bug](https://cloud.githubusercontent.com/assets/3769532/6108509/e2748230-b041-11e4-9506-496673caaa11.gif)

If you move the mouse kind of fast, it introduces a 'ghost' tooltip that briefly shows up and goes away.  This is happening in the latest Chrome and using nvd3 development.

@liquidpele I'd like to assign this to Drew Peterson, does he have a github account?

**Comment by petersondrew** [comment]
@robinfhu I do have a github account! The commits must have been done with my work email address.

I'll take a look, do you have a repro that I can start looking at?

**Comment by liquidpele** [comment]
are... are we creating/destroying the tooltip instead of just moving it?

**Comment by robinfhu** [comment]
Hi @petersondrew  thanks for getting back!  To reproduce, pull the latest 'development' branch, open the file: test/lineChartTest.html

**Comment by petersondrew** [comment]
@liquidpele When you move the mouse it just uses css transforms to move the tooltip.
@robinfhu This was done without using fastdom, correct? Just using the lineChartTest as-is?

**Comment by petersondrew** [comment]
@robinfhu Ah ok, it looks like it's happening only when the mouse leaves the chart and comes back. What's supposed to happen, and what happens in the branch I made my changes to the tooltip code in, is the tooltip element is hidden when leaving the chart and shown again when returning. Something must have broken that since I submitted my PR.
I'll take a look and see if I can figure out what's going on.

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (317/300 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:35673 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84)
	(envelope-from <noreply@github.com>)
	id 1YKrgW-002YWk-1G
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:59:45 +0200
Date: Mon, 09 Feb 2015 08:59:37 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1423501177;
	bh=ndTMrMrGnPQEJRkwL7bVE2c4wbM0BkP5gSHXGOR9H5s=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=geX+BtrFsOAyJ84YlaRET/Jp9xsStjGExGGobV9mAsWSNS715VJehXasY9n0UuKtU
	 WLCVagOqyuju1y/RPzT4Xu6WGC0JV1PPcneT9JONYZ0v4fL/3lkVD7imLQfjUE/9ko
	 vTA1+ElnkWMS5uOFZ5WeK/Uxypus+HfrnuFB+UOM=

**Comment by petersondrew** [comment]
@robinfhu @liquidpele  It would appear the problem is (here)[https://github.com/novus/nvd3/blob/master/src/tooltip.js#L487]. When mousing out of the chart that throws an exception because the parentNode of removeMe is null.

I'll see if I can find why that's happening, if you beat me to it let me know!

**Comment by robinfhu** [comment]
@petersondrew thanks, see if you can fix it and submit a PR.  Also, I don't really know what 'fastdom' is.  Is it this: https://github.com/wilsonpage/fastdom

Is it another library we need to include?

**Comment by petersondrew** [comment]
@robinfhu It looks like 09df70f3 reverted the cleanup code from my original PR. 
@RenatoUtsch can you fill us in on why you reverted the cleanup code from my PR? Did it break something?

**Comment by petersondrew** [comment]
@robinfhu That is fastdom, it's an optional dependency. If we find it at runtime the code uses batched dom operations to avoid thrashing the dom.

**Comment by portante** [comment]
@petersondrew, can we end this cycle with a unit test that covers the functionality that you expect and also ensures the regression is not happening as well?

**Comment by petersondrew** [comment]
@portante Yes at this point that's probably a must.

**Comment by petersondrew** [comment]
FYI - The PR that introduced the regression is https://github.com/nvd3-community/nvd3/pull/51

**Comment by RenatoUtsch** [comment]
@petersondrew I reverted the cleanup code from your PR because it stopped to actually remove the divs after the user moused out.
This would be OK if the tooltip div was reused instead of creating a new one, but when I made this second pull request, new divs were being created instead of reusing the existing one.

Looking back now, this is probably because of the other regression I made in PR #42 (specially 0f518d7). The problem I was having is that I am trying to make NVD3 properly work with shadow dom to create a NVD3 polymer element. I noticed that when trying to select elements by ID, because of shadow dom, it always returns null because the elements are inside the shadow dom, and not in the normal body.

The selection by ID not working resulted in this:
http://i.imgur.com/N80Pzjz.png

After making these regressions I looked at the nvd3 examples and they appeared OK, I didn't notice anything wrong here. Probably a unit test will be needed.

Maybe a possible solution is enforcing the creation of tooltips outside the shadow dom. Then the selection by ID will work properly i guess...

**Comment by petersondrew** [comment]
@RenatoUtsch I wonder if you were missing the CSS rules in your branch? As soon as the tooltip is marked for removal the CSS rules for that class would hide it, which is how it was working when I submitted my PR.

I'm going to restore the tooltip creation and cleanup functions to how they were prior to your pull request and add some additional unit tests if necessary.

**Comment by RenatoUtsch** [comment]
It is not the CSS rules. The problem is with the ids. If you try to reference a div with a certain id that was created inside a shadow dom from outside the shadow dom, the search for the div's id will return nothing.

This is a problem with how the tooltip code works in nvd3. I will have to devise a better solution for it.

**Comment by petersondrew** [comment]
Understood, I was thinking your shadow dom integration issue was only related to tooltip creation, not hiding as well.

**Comment by RenatoUtsch** [comment]
The issue is that the CSS properties are never applied because of trying to identify the tooltips by the id, when it is in the shadow dom.

Anyway, sorry for the problems with the rollback.

**Comment by petersondrew** [comment]
No worries

**Comment by liquidpele** [comment]
I'll leave verifying/closing this to robin since he saw the original issue.

**Comment by robinfhu** [comment]
This has been solved

**Comment by robinfhu** [comment]
@petersondrew I think there are still issues: https://github.com/novus/nvd3/issues/771
