### ISSUE TITLE
The pie/donut option "legendPosition" with value 'right' is buggy

### ISSUE THREAD

**Issue by liquidpele** [novus/nvd3#862]
I tried to use this (it was a PR from a community member) and the legend gets cut off easily and when you disable/enable slices it will jump left and right.

**Comment by liquidpele** [comment]
@driehuis can you look at this since it was your PR?   

The original PR is:  https://github.com/nvd3-community/nvd3/pull/7

**Comment by driehuis** [comment]
Will do. To get met started quickly, could you point to a gist that reproduces the issue?

**Comment by liquidpele** [comment]
I used the pieChart.html and donutChart.html examples in the project, and used legendPosition('right') on them, then I checked it out in chrome and it was cut off some, so I adjusted the right margin to zero to make room (which should be unnecessary anyway) and then it was jumping when I clicked on it.

**Comment by liquidpele** [comment]
Oh, and I was using the half-circle examples, so that might have something to do with it.

**Comment by driehuis** [comment]
Nah, it's obviously deeper than just using half-circle donuts. I have reproduced the issue, and also saw where my own testing was off so that I missed this problem completely.

I always religiously try to avoid duplicating settings in CSS and JS or HTML, and I had not spotted that the nvd3 examples set an svg size in css, and define identical sizes in JavaScript. That oversight on my part explains a lot of seemingly undefined behavior I saw with nvd3. Oh well, I honestly believed I had not made matters worse.

I'll try to set aside some time to really fix this. In the mean time, feel free to back out the pull request. I hate broken code as much as the next guy :-)

I'll admit to being a tad confused, seeing this issue in the Novus repo, wasn't this supposed to be in the nvd3-community repo?

**Comment by liquidpele** [comment]
Na, I'll just leave it in for now, the bug doesn't affect anything unless you explicitly try to use that feature so it's no big deal.   Novus decided they wanted to put time toward nvd3 again, and added myself and another community member to their org so I have full access here now too.  Using this repo is easier since it gets way more traffic/etc.

**Comment by driehuis** [comment]
Just created a pull request. The new code is not ideal, but it's the best I can do at short notice. What should be done is to change the legend code to prefer a vertical orientation when drawing in a narrow, tall space, to optimize screen real estate.

This code seems robust in the face of tinkering with width and height, and I have not seen jumps in legend position with the new code.

**Comment by driehuis** [comment]
P.S. Is nvd3-community now officially dead? In that case I'll nuke my fork and start a fresh one to facilitate pull requests.

**Comment by liquidpele** [comment]
nvd3-community is in hibernation - yea you should fork the novus one and work on that at this point.

**Comment by liquidpele** [comment]
made a PR from nvd3-community:   https://github.com/novus/nvd3/pull/875

**Comment by liquidpele** [comment]
This is still a little buggy.  Using this feature on the existing pieChart.html example, on the half-circle, it makes the circle show up centered vertically but the legend isn't so they look off, then on the first automated update it all shifts a little.   Using chrome.

**Comment by driehuis** [comment]
First of all, that's what you get for squeezing a round peg into a square hole  :-)  The CSS+JS specify a square 350x350 canvas for an image that is composed of a 175x100 piechart, side by side with a 175x100 legend. I would think that users, who want a legend to the right, have that preference because the screen real estate they're dealing with is elongated, say a 2:1 aspect ratio (or as in my use case, a 3:1 aspect ratio). If you try a 350x175 canvas the graph looks much better, even with the legend code as-is.

The pie chart attempts to center itself vertically in the available space, while the legend attempts to align to the top. That causes the offset look of the legend. The legend code should be modified to vertically center itself when using legendPosition=right.

I have not found a cause yet for the jump. I see it, but it's only on the first data update. On subsequent updates, the screen stays stable. It has to do with recalculating the margins on every pass, but I haven't figured this one out precisely just yet. I will look into this deeper when I find some time.

**Comment by liquidpele** [comment]
Haha, yea, the chart being small I'm not worried about, that's expected.  The legend not being vertically centered there I think should be fixed, since it should be lined up with the chart if it's on the side, and the jump obviously should be fixed.   :)

**Comment by rreinhardt9** [comment]
First of all, thanks for all the hard work on such an awesome library! 
I'm really new to d3 and this lib, but I just ran into this problem as I tried to fit the pieChart into our existing app. From what I can tell, the problem seems to be [here](https://github.com/novus/nvd3/blob/development/src/models/pieChart.js#L131). On first load, if `legend.width()` is not > `availableWidth/2` (as in a full screen chart, for example) then availableWidth does not get adjusted for legend.width() and it translates it right off the page in line 139. When you update the chart, availableWidth has changed because margin.right has changed then therefore it updates availableWidth appropriately at that point. The following works for me:

```ruby 
                   # Current code
                    if ( margin.right != legend.width()) {
                        if (legend.width() > availableWidth / 2) {
                            legend.width(availableWidth / 2);
                            availableWidth -= legend.width();
                        }
                        margin.right = legend.width();
                    }
```

```ruby 
                   # This change works for me
                    if ( margin.right != legend.width()) {
                        if (legend.width() > availableWidth / 2) {
                            legend.width(availableWidth / 2);
                        }
                        margin.right = legend.width();
                        availableWidth -= legend.width();
                    }
``` 
There is still trouble if you resize it smaller and then bigger, because chart.width() remains set to a smaller size, but I haven't figured out a fix for that yet. Hopefully this helps;
If we end up needing this in our app, then I can try to put together a PR if it would help.

**Comment by liquidpele** [comment]
Hopefully fixed now...

**Comment by venkatasunil4** [comment]
Hi, 
 I am using latest nvd3 with bootstrap and angularJS. The pie chart initially displays small but on window resize, the actual size of pie chart is displayed. Is there a solution to display pie chart with correct size on load ?
