### ISSUE TITLE
horizon chart

### ISSUE THREAD

**Issue by yppeaxy** [novus/nvd3#953]
Hi!
thank you for an awesome component! 

Question: I do not see a model for a horizon chart. Is there a way to create it using nvd3 and/or are you planning to implement it?

**Comment by liquidpele** [comment]
Hi there!  Actually, older versions of nvd3 did have a horizon chart, but it didn't work quite right so I removed it since I'd never seen anyone actually make use of it.   Feel free to re-implement it and fix it up and send us a pull request and we'll take a look at it again :)

Here is a link to the previous version's horizon chart example:

https://github.com/novus/nvd3/blob/v1.2.1/examples/horizon.html

**Comment by yppeaxy** [comment]
Thank you for the fast response! 

Yeah, I did find this example, unfortunately it gives me an error at line 123. 
My data is not sine() but a time series data[[14287356000001,-0.655],[14287404150001,1.345 ],....], so when 'i' at line 121 is equal to 14287356000001 data[i][1] is not very happy

I already wrote an angular directive that is doing a simple wrap of a d3.horizon() but I was hopping to be able to use nvd3 tooltips

**Comment by liquidpele** [comment]
Yea, there definitely might be issues, especially if you try to use it with the latest version of nvd3 instead of that old version.  Unfortunately it's not a big priority for us, but if you put in the work to do it then please send us a pull request :)    

https://github.com/novus/nvd3/tree/development#a-few-rules-for-pull-requests

**Comment by liquidpele** [comment]
Going to go ahead and close this one, let me know if you have any specific questions though, cheers!
