### ISSUE TITLE
Documentation about changing new tooltips with contentGenerator

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#994]
@liquidpele 

Where can I find documentation about changing the tooltip content with contentGenerator? The explanation I found at the documentation.html page was insufficient, it doesn't explain how to change the content of a tooltip.

I didn't find any examples in the examples folder also.

**Comment by liquidpele** [comment]
Well, unfortunately each chart sends data to the tooltips in a little different format... so that's why in the example in the doc I had it print out the whole thing as a json object, so you could see what it was sending it :)

Using that option in some of the examples is a good idea... unfortunately I don't have much free time right now... any chance you could add some?

**Comment by RenatoUtsch** [comment]
The thing is, I couldn't find this JSON object you're talking about.

As soon as I learn how to change the content I can do that =)

**Comment by RenatoUtsch** [comment]
Oh, you can ignore my comment above, I just did a console.log(d); inside the contentGenerator hehe

**Comment by liquidpele** [comment]
JSON is a global object in modern browsers that lets you load and stringify json without doing an eval.   

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON

**Comment by RenatoUtsch** [comment]
No, I wasn't talking about the JSON global object, but about the json input object to the contentGenerator hehe
